# Generated by Django 5.2.6 on 2025-09-16 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Asignador', 'Asignador'), ('Administrador', 'Administrador')], default='Asignador', max_length=20),
        ),
    ]
