# Generated by Django 5.2.7 on 2025-12-01 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Asignador', 'Asignador'), ('Administrador', 'Administrador'), ('Ambos', 'Ambos')], default='Asignador', max_length=20),
        ),
    ]
