# Generated by Django 5.2.7 on 2025-12-02 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('asignador', 'asignador'), ('administrador', 'administrador'), ('ambos', 'ambos')], default='asignador', max_length=20),
        ),
    ]
