version: "3.9"

name: plataforma-formulario

services:
  db_usuarios:
    image: mysql:8.0               # Imagen oficial de MySQL versión 8.0
    container_name: db_usuarios    # Nombre del contenedor (visible en Docker)
    restart: always                # Reinicia el contenedor automáticamente si se detiene
    env_file:
      - .env  # Archivo .env con variables de entorno
    environment:
      MYSQL_DATABASE: ${AUTH_DB_NAME}        # Nombre de la base de datos (definido en .env)
      MYSQL_USER: ${AUTH_DB_USER}            # Usuario de la base de datos (definido en .env)
      MYSQL_PASSWORD: ${AUTH_DB_PASSWORD}    # Contraseña del usuario (definida en .env)
      MYSQL_ROOT_PASSWORD: ${AUTH_DB_PASSWORD}  # Contraseña del root (requerida por MySQL)
    volumes:
      - volumen_db_usuarios:/var/lib/mysql # Monta un volumen persistente en /var/lib/mysql TODOS USAR TAMBIEN /var/lib/mysql POR CONVENCIÓN 
    networks:
      - app-net
    ports:
      - "3306:3306"  # Expone el puerto 3306 (MySQL) para acceso desde fuera del contenedor
    # IMPORTANTE Healthcheck para asegurarse de que MySQL esté listo antes de que Django intente conectarse
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "db_usuarios", "-u${AUTH_DB_USER}", "-p${AUTH_DB_PASSWORD}"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 20s

  db_formulario:
    image: mysql:8.0
    container_name: db_formulario
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${FORM_DB_NAME}
      MYSQL_USER: ${FORM_DB_USER}
      MYSQL_PASSWORD: ${FORM_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${FORM_DB_ROOT_PASSWORD}
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "db_usuarios", "-u${AUTH_DB_USER}", "-p${AUTH_DB_PASSWORD}"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 20s
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-net

  servicio_seguridad_jwt:              # 👈 tu micro de seguridad
    build:
      context: ./servicio_seguridad_jwt   # 👈 carpeta donde está el Dockerfile de este micro
      dockerfile: Dockerfile
    container_name: servicio_seguridad_jwt_app
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db_formulario:3306/${AUTH_DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Bogota
      SPRING_DATASOURCE_USERNAME: ${AUTH_DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${AUTH_DB_PASSWORD}
    depends_on:
       db_usuarios:
         condition: service_healthy
    ports:
      - "8081:8080"
    networks:
      - app-net
    restart: unless-stopped

  gestion_formulario:                  # 👈 tu micro Django
    build:
      context: ./gestion-formulario    # 👈 carpeta donde está el Dockerfile de Django
      dockerfile: Dockerfile
    container_name: gestion_formulario_app
    env_file:
      - .env
    environment:
      DB_NAME: ${FORM_DB_NAME}
      DB_USER: ${FORM_DB_USER}
      DB_PASSWORD: ${FORM_DB_PASSWORD}
      DB_HOST: ${FORM_DB_HOST}
      DB_PORT: ${FORM_DB_PORT}
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: ${RABBITMQ_USER:-guest}
      RABBITMQ_PASS: ${RABBITMQ_PASS:-guest}
      RABBITMQ_EXCHANGE: asignacion.electivas
    depends_on:
      db_formulario:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    command: >
      sh -c "
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000
      "
    ports:
      - "8000:8000"
    networks:
      - app-net
    restart: unless-stopped
  
  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    ports:
      - "5672:5672"   # Puerto para conexiones AMQP
      - "15672:15672" # Puerto para la interfaz de administración
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics -q ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - app-net
    restart: unless-stopped

volumes:
  mysql_data:
  volumen_db_usuarios:

networks:
  app-net:
    driver: bridge