# Generated by Django 5.2.6 on 2025-11-03 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('fac_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('fac_nombre', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('pro_codigo', models.CharField(max_length=225, primary_key=True, serialize=False)),
                ('pro_nombre', models.CharField(max_length=150, unique=True)),
                ('pro_activo', models.BooleanField(default=True)),
                ('fac_codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programas', to='gestion_electivas.facultad')),
            ],
        ),
        migrations.CreateModel(
            name='Electiva',
            fields=[
                ('ele_codigo', models.CharField(max_length=225, primary_key=True, serialize=False)),
                ('ele_nombre', models.CharField(max_length=150, unique=True)),
                ('ele_estado', models.BooleanField(default=True)),
                ('pro_codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electivas', to='gestion_electivas.programa')),
            ],
        ),
    ]
