# Generated by Django 5.2.6 on 2025-12-10 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_electivas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electiva',
            name='ele_cupos',
            field=models.PositiveIntegerField(),
        ),
    ]
