# Generated by Django 5.2.7 on 2025-10-04 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('pro_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('pro_nombre', models.CharField(max_length=150, unique=True)),
                ('fac_codigo', models.IntegerField()),
                ('pro_activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('est_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('est_nombre', models.CharField(max_length=120)),
                ('est_apellido', models.CharField(max_length=120)),
                ('est_correo', models.EmailField(max_length=254, unique=True)),
                ('pro_codigo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estudiantes', to='referencias.programa')),
            ],
        ),
        migrations.CreateModel(
            name='Electiva',
            fields=[
                ('ele_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('ele_nombre', models.CharField(max_length=150, unique=True)),
                ('ele_estado', models.BooleanField(default=True)),
                ('pro_codigo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='electivas', to='referencias.programa')),
            ],
        ),
    ]
