# Generated by Django 5.2.7 on 2025-10-26 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('pro_codigo', models.CharField(max_length=225, primary_key=True, serialize=False)),
                ('pro_nombre', models.CharField(max_length=150, unique=True)),
                ('fac_codigo', models.IntegerField()),
                ('pro_activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('est_codigo', models.BigIntegerField(primary_key=True, serialize=False)),
                ('est_nombre', models.CharField(max_length=120)),
                ('est_apellido', models.CharField(max_length=120)),
                ('est_correo', models.EmailField(max_length=254, unique=True)),
                ('pro_codigo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estudiantes', to='referencias.programa')),
            ],
        ),
        migrations.CreateModel(
            name='Electiva',
            fields=[
                ('ele_codigo', models.CharField(max_length=225, primary_key=True, serialize=False)),
                ('ele_nombre', models.CharField(max_length=150, unique=True)),
                ('ele_estado', models.BooleanField(default=True)),
                ('pro_codigo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='electivas', to='referencias.programa')),
            ],
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('ofe_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('ofe_anio', models.PositiveIntegerField()),
                ('ofe_num_semestre', models.PositiveSmallIntegerField(choices=[(1, 'I'), (2, 'II')])),
                ('ele_codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='referencias.electiva')),
                ('pro_codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='referencias.programa')),
            ],
            options={
                'ordering': ['-ofe_anio', '-ofe_num_semestre'],
                'constraints': [models.UniqueConstraint(fields=('ofe_anio', 'ofe_num_semestre', 'ele_codigo', 'pro_codigo'), name='unique_oferta_asignacion')],
            },
        ),
        migrations.CreateModel(
            name='SeleccionEstudianteElectiva',
            fields=[
                ('sel_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('sel_anio', models.IntegerField()),
                ('sel_num_semestre', models.IntegerField(choices=[(1, 'Primer semestre'), (2, 'Segundo semestre')])),
                ('sel_prioridad', models.IntegerField()),
                ('ele_codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='referencias.electiva')),
                ('est_codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='referencias.estudiante')),
            ],
            options={
                'db_table': 'Seleccion_estudiante_electiva',
                'ordering': ['est_codigo', 'sel_prioridad'],
                'unique_together': {('sel_anio', 'sel_num_semestre', 'est_codigo', 'ele_codigo', 'sel_prioridad')},
            },
        ),
    ]
