# Generated by Django 5.2.7 on 2025-10-11 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referencias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='est_codigo',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
