# Generated by Django 5.2.7 on 2025-10-11 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referencias', '0002_alter_estudiante_est_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='est_codigo',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
