# Generated by Django 5.2.7 on 2025-10-21 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referencias', '0004_oferta_seleccionestudianteelectiva'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('fac_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('fac_nombre', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='electiva',
            name='ele_codigo',
            field=models.CharField(max_length=225, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='programa',
            name='pro_codigo',
            field=models.CharField(max_length=225, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='programa',
            name='fac_codigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programas', to='referencias.facultad'),
        ),
    ]
