"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure--ez^6x1!rwr0vf21&^p+-w_t3ob$+!xhw9n^cqwz+p4lj11ren'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'gestion_hojas_de_calculo',
    'referencias',
    'worker.apps.WorkerConfig', 
    # Apps de terceros requeridas
    'rest_framework',        
    'import_export',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    # Conexión a la base de datos principal de este microservicio
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': config('ASIGNACION_DB_NAME'),
        'USER': config('ASIGNACION_DB_USER'),
        'PASSWORD': config('ASIGNACION_DB_PASSWORD'),
        'HOST': config('ASIGNACION_DB_HOST'), # Debería ser 'db_asignacion'
        'PORT': config('ASIGNACION_DB_PORT'), # Debería ser '3306' (interno de Docker)
    },
    # --- CONFIGURACIÓN MULTI-DB ---
    # Añadimos la conexión a la base de datos del microservicio de formularios.
    # Esto es necesario para que el comando `sync_databases` pueda leer los datos de origen.
    'formulario': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': config('FORM_DB_NAME'),
        'USER': config('FORM_DB_USER'),
        'PASSWORD': config('FORM_DB_PASSWORD'),
        'HOST': config('FORM_DB_HOST'), # Debería ser 'db_formulario'
        'PORT': config('FORM_DB_PORT'), # Debería ser '3306' (interno de Docker)
    }
    # Si no se usa un router de base de datos, la conexión 'formulario' puede ser eliminada.
}



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
