
CODIGO_SISTEMAS = 1
CODIGO_AUTOMATICA = 2
CODIGO_ELECTRONICA = 3

CREDITOS_ELECTIVAS = 3
CREDITOS_TOTALES_OBLIGATORIOS_SIS = 80
CREDITOS_TOTALES_OBLIGATORIOS_AUT = 75
CREDITOS_TOTALES_OBLIGATORIOS_ELE = 70

CREDITOS_NIVELADOS_8_SIS = 112
CREDITOS_NIVELADOS_8_AUT = 123
CREDITOS_NIVELADOS_8_ELE = 116

CREDITOS_NIVELADOS_9_SIS = 132
CREDITOS_NIVELADOS_9_AUT = 130
CREDITOS_NIVELADOS_9_ELE = 127

CREDITOS_NIVELADOS_10_SIS = 151
CREDITOS_NIVELADOS_10_AUT = 159
CREDITOS_NIVELADOS_10_ELE = 155

