# Generated by Django 5.2.6 on 2025-10-12 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_electivas', '0001_initial'),
        ('gestion_estudiantes', '0004_alter_estudiante_est_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeleccionEstudianteElectiva',
            fields=[
                ('sel_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('sel_anio', models.IntegerField()),
                ('sel_num_semestre', models.IntegerField(choices=[(1, 'Primer semestre'), (2, 'Segundo semestre')])),
                ('sel_prioridad', models.IntegerField()),
                ('ele_codigo', models.ForeignKey(db_column='ele_codigo', on_delete=django.db.models.deletion.CASCADE, to='gestion_electivas.electiva')),
                ('est_codigo', models.ForeignKey(db_column='est_codigo', on_delete=django.db.models.deletion.CASCADE, to='gestion_estudiantes.estudiante')),
            ],
            options={
                'db_table': 'Seleccion_estudiante_electiva',
                'unique_together': {('sel_anio', 'sel_num_semestre', 'est_codigo', 'ele_codigo', 'sel_prioridad')},
            },
        ),
    ]
