# Generated by Django 5.2.6 on 2025-10-17 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_electivas', '0001_initial'),
        ('gestion_estudiantes', '0004_alter_estudiante_est_codigo'),
        ('seleccion_electivas', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seleccionestudianteelectiva',
            unique_together={('sel_anio', 'sel_num_semestre', 'est_codigo', 'ele_codigo'), ('sel_anio', 'sel_num_semestre', 'est_codigo', 'sel_prioridad')},
        ),
    ]
