# Generated by Django 5.2.6 on 2025-11-09 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_electivas', '0001_initial'),
        ('gestion_estudiantes', '0001_initial'),
        ('seleccion_electivas', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='seleccionestudianteelectiva',
            constraint=models.CheckConstraint(condition=models.Q(('sel_anio__gte', 2025)), name='sel_anio_no_inferior_anio_actual'),
        ),
        migrations.AddConstraint(
            model_name='seleccionestudianteelectiva',
            constraint=models.CheckConstraint(condition=models.Q(('sel_prioridad__gt', 0)), name='sel_prioridad_mayor_que_cero'),
        ),
    ]
