# Generated by Django 5.2.6 on 2025-09-23 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_electivas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('est_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('est_nombre', models.CharField(max_length=120)),
                ('est_apellido', models.CharField(max_length=120)),
                ('est_correo', models.EmailField(max_length=254, unique=True)),
                ('pro_codigo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estudiantes', to='gestion_electivas.programa')),
            ],
        ),
    ]
