# Generated by Django 5.2.6 on 2025-10-11 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='est_codigo',
            field=models.IntegerField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
