# Generated by Django 5.2.6 on 2025-10-11 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_estudiantes', '0002_alter_estudiante_est_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='est_codigo',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
