# Generated by Django 5.2.6 on 2025-09-23 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_electivas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta_electiva',
            fields=[
                ('ofe_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('ofe_anio', models.PositiveIntegerField()),
                ('ofe_num_semestre', models.PositiveSmallIntegerField(choices=[(1, 'I'), (2, 'II')])),
                ('ele_codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='gestion_electivas.electiva')),
                ('pro_codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='gestion_electivas.programa')),
            ],
            options={
                'ordering': ['-ofe_anio', '-ofe_num_semestre'],
                'constraints': [models.UniqueConstraint(fields=('ofe_anio', 'ofe_num_semestre', 'ele_codigo', 'pro_codigo'), name='unique_oferta_electiva')],
            },
        ),
    ]
