# Generated by Django 5.2.6 on 2025-12-10 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_electivas', '0001_initial'),
        ('gestion_oferta_electiva', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta_formulario',
            fields=[
                ('ofefor_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('ofefor_anio', models.PositiveIntegerField()),
                ('ofefor_num_semestre', models.PositiveSmallIntegerField(choices=[(1, 'I'), (2, 'II')])),
                ('ofefor_cantidad_electivas', models.PositiveIntegerField()),
                ('pro_codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertaformulario', to='gestion_electivas.programa')),
            ],
            options={
                'ordering': ['-ofefor_anio', '-ofefor_num_semestre'],
                'constraints': [models.UniqueConstraint(fields=('ofefor_anio', 'ofefor_num_semestre', 'pro_codigo'), name='unique_oferta_formulario')],
            },
        ),
    ]
