# Generated by Django 5.2.7 on 2025-12-10 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('referencias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilAcademico',
            fields=[
                ('perfil_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('promedio', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('num_electivas_cursadas', models.IntegerField(default=0)),
                ('creditos_aprob_total', models.IntegerField(default=0)),
                ('num_periodos_matriculados', models.IntegerField(default=0)),
                ('nivelado', models.BooleanField(default=False)),
                ('porcentaje_avance', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('estado', models.BooleanField(default=False)),
                ('perfil_anio', models.IntegerField()),
                ('perfil_semestre', models.IntegerField()),
                ('est_codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfiles_academicos', to='referencias.estudiante')),
            ],
            options={
                'verbose_name': 'Perfil Académico',
                'verbose_name_plural': 'Perfiles Académicos',
                'unique_together': {('est_codigo', 'perfil_anio', 'perfil_semestre')},
            },
        ),
    ]
