# Generated by Django 5.2.7 on 2025-12-09 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_hojas_de_calculo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilacademico',
            name='perfil_anio',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='perfilacademico',
            name='perfil_semestre',
            field=models.IntegerField(),
        ),
    ]
