# Generated by Django 5.2.7 on 2025-10-21 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_hojas_de_calculo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilacademico',
            name='creditos_aprob_oblig',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='perfilacademico',
            name='creditos_aprob_total',
            field=models.IntegerField(default=0),
        ),
    ]
