# Generated by Django 5.2.7 on 2025-10-23 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_hojas_de_calculo', '0002_perfilacademico_creditos_aprob_oblig_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilacademico',
            name='creditos_aprob_oblig',
        ),
    ]
