# Generated by Django 5.2.7 on 2025-12-10 03:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('referencias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id_asignacion', models.BigAutoField(primary_key=True, serialize=False)),
                ('anio', models.PositiveSmallIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)])),
                ('asi_num_semestre', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2')], db_index=True)),
                ('en_lista_espera', models.BooleanField(db_index=True, default=False)),
                ('ele_codigo', models.ForeignKey(db_column='ele_codigo', on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='referencias.electiva')),
                ('est_codigo', models.ForeignKey(db_column='est_codigo', on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='referencias.estudiante')),
            ],
            options={
                'db_table': 'asignacion',
                'indexes': [models.Index(fields=['est_codigo'], name='idx_asig_est'), models.Index(fields=['ele_codigo'], name='idx_asig_elec'), models.Index(fields=['en_lista_espera'], name='idx_asig_espera')],
                'constraints': [models.UniqueConstraint(fields=('anio', 'asi_num_semestre', 'est_codigo', 'ele_codigo'), name='uniq_asignacion_periodo_est_elec')],
            },
        ),
    ]
