# Generated by Django 5.2.7 on 2025-10-28 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion', '0001_initial'),
        ('referencias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='en_lista_espera',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='asignacion',
            index=models.Index(fields=['en_lista_espera'], name='idx_asig_espera'),
        ),
    ]
