# Generated by Django 5.2.7 on 2025-12-10 03:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcesoAsignacion',
            fields=[
                ('pa_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('pa_paso_actual', models.PositiveSmallIntegerField(choices=[(1, 'creado'), (2, 'archivos-guardados'), (4, 'nivelados-gestionados'), (5, 'asignacion-realizada'), (6, 'finalizado')], default=1, help_text='1=creado, 2=archivos-guardados, 4=nivelados-gestionados, 5=asignacion-realizada, 6=finalizado')),
                ('pa_anio', models.PositiveSmallIntegerField(help_text='Ej: 2025', validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)])),
                ('pa_num_semestre', models.PositiveSmallIntegerField(help_text='1 ó 2', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)])),
                ('pa_fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('pa_ultima_fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('pa_estado', models.PositiveSmallIntegerField(choices=[(1, 'activo'), (2, 'inactivo')], default=1, help_text='1=activo, 2=inactivo')),
            ],
            options={
                'ordering': ['-pa_fecha_creacion'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('pa_estado', 1)), fields=('pa_estado',), name='uniq_un_proceso_activo_global'), models.UniqueConstraint(fields=('pa_anio', 'pa_num_semestre'), name='uniq_proceso_por_anio_semestre')],
            },
        ),
    ]
