# Generated by Django 5.2.7 on 2025-10-13 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcesoAsignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('paso_actual', models.PositiveSmallIntegerField(default=1)),
                ('datos_temporales', models.JSONField(blank=True, default=dict)),
                ('estado', models.CharField(choices=[('EN_CURSO', 'En Curso'), ('BORRADOR', 'Borrador')], default='EN_CURSO', max_length=12)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
